-- Delay reasons by airport
Create Or Replace View Delay_Reason as
SELECT f.ORIGIN_AIRPORT,f.AIR_SYSTEM_DELAY, f.SECURITY_DELAY, f.AIRLINE_DELAY, f.LATE_AIRCRAFT_DELAY, f.WEATHER_DELAY
FROM FLIGHTS f
WHERE f.DEPARTURE_DELAY > 0 OR f.ARRIVAL_DELAY > 0
GROUP BY f.ORIGIN_AIRPORT,f.AIR_SYSTEM_DELAY, f.SECURITY_DELAY, f.AIRLINE_DELAY, f.LATE_AIRCRAFT_DELAY, f.WEATHER_DELAY;

