-- On time percentage of each airline for the year 2015 
-- NOTE: This is based on DEPARTURE. We can modify it to change to ARRIVAL. 
CREATE OR REPLACE VIEW ON_TIME AS
SELECT T.AIRLINE, C, C2,ROUND(C*100/C2,2) as C3 
FROM (SELECT AIRLINE, count(*) AS C FROM FLIGHTS WHERE DEPARTURE_DELAY <= 0 AND Year=2015 GROUP BY AIRLINE) T 
JOIN (SELECT AIRLINE, count(*) AS C2 FROM FLIGHTS WHERE Year=2015 GROUP BY AIRLINE) T2 ON (T.AIRLINE=T2.AIRLINE)
ORDER BY C3 DESC;