-- Airline with the most unique routes  
Create Or replace view Total_Unique_Route as 
SELECT COUNT(*) TOTAL_Unique_ROUTE, AIRLINE
FROM 		
(
	SELECT DISTINCT AIRLINE, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	FROM FLIGHTS f
) b GROUP BY b.AIRLINE 
HAVING COUNT(*) =
( 
	SELECT MAX(TOTAL_ROUTE) MAX_TOTAL_ROUTE
	FROM 
	( 
		SELECT COUNT(*) TOTAL_ROUTE, AIRLINE FROM
		(
			SELECT DISTINCT AIRLINE, ORIGIN_AIRPORT, DESTINATION_AIRPORT
			FROM FLIGHTS f
		) b GROUP BY b.AIRLINE 
	) b
)